import type { AssetDefinition, AvatarDefinition } from "@/lib/types";

const characterPath = "/assets/modern-tiles-free/characters";
const interiorsPath = "/assets/modern-tiles-free/interiors";

export const avatarDefinitions: AvatarDefinition[] = [
  {
    id: "adam",
    name: "Adam",
    src: `${characterPath}/Adam_idle_anim_16x16.png`,
    runSrc: `${characterPath}/Adam_run_16x16.png`,
    color: "#8fb34f",
    role: "Analista de hojas",
    frame: { width: 16, height: 32 },
  },
  {
    id: "alex",
    name: "Alex",
    src: `${characterPath}/Alex_idle_anim_16x16.png`,
    runSrc: `${characterPath}/Alex_run_16x16.png`,
    color: "#d59b63",
    role: "Operador de flujos",
    frame: { width: 16, height: 32 },
  },
  {
    id: "amelia",
    name: "Amelia",
    src: `${characterPath}/Amelia_idle_anim_16x16.png`,
    runSrc: `${characterPath}/Amelia_run_16x16.png`,
    color: "#b98374",
    role: "Curadora de informes",
    frame: { width: 16, height: 32 },
  },
  {
    id: "bob",
    name: "Bob",
    src: `${characterPath}/Bob_idle_anim_16x16.png`,
    runSrc: `${characterPath}/Bob_run_16x16.png`,
    color: "#7c9ec8",
    role: "Archivista veloz",
    frame: { width: 16, height: 32 },
  },
];

export const assetDefinitions: AssetDefinition[] = [
  ...avatarDefinitions.map((avatar) => ({
    key: `avatar_${avatar.id}`,
    name: avatar.name,
    category: "character" as const,
    src: avatar.src,
    gridSize: { w: 1, h: 2 },
  })),
  {
    key: "office_floor_01",
    name: "Suelo claro",
    category: "floor",
    src: `${interiorsPath}/Room_Builder_free_16x16.png`,
    frame: { x: 0, y: 0, w: 16, h: 16 },
    gridSize: { w: 1, h: 1 },
  },
  {
    key: "desk_basic",
    name: "Mesa de trabajo",
    category: "furniture",
    src: `${interiorsPath}/Interiors_free_16x16.png`,
    frame: { x: 16, y: 48, w: 32, h: 16 },
    gridSize: { w: 2, h: 1 },
    collidable: true,
  },
  {
    key: "desk_corner",
    name: "Mesa con terminal",
    category: "furniture",
    src: `${interiorsPath}/Interiors_free_16x16.png`,
    frame: { x: 0, y: 848, w: 48, h: 32 },
    gridSize: { w: 3, h: 2 },
    collidable: true,
  },
  {
    key: "terminal_workstation",
    name: "Terminal de automatizacion",
    category: "furniture",
    src: `${interiorsPath}/Interiors_free_16x16.png`,
    frame: { x: 64, y: 880, w: 32, h: 32 },
    gridSize: { w: 2, h: 2 },
    collidable: true,
  },
  {
    key: "desk_wide",
    name: "Mesa doble",
    category: "furniture",
    src: `${interiorsPath}/Interiors_free_16x16.png`,
    frame: { x: 32, y: 336, w: 48, h: 24 },
    gridSize: { w: 3, h: 2 },
    collidable: true,
  },
  {
    key: "file_cabinet",
    name: "Archivador",
    category: "furniture",
    src: `${interiorsPath}/Interiors_free_16x16.png`,
    frame: { x: 160, y: 544, w: 32, h: 32 },
    gridSize: { w: 2, h: 2 },
    collidable: true,
  },
  {
    key: "bookshelf_basic",
    name: "Estanteria",
    category: "furniture",
    src: `${interiorsPath}/Interiors_free_16x16.png`,
    frame: { x: 96, y: 624, w: 48, h: 32 },
    gridSize: { w: 3, h: 2 },
    collidable: true,
  },
  {
    key: "bookshelf_wide",
    name: "Biblioteca doble",
    category: "furniture",
    src: `${interiorsPath}/Interiors_free_16x16.png`,
    frame: { x: 144, y: 1216, w: 96, h: 48 },
    gridSize: { w: 6, h: 3 },
    collidable: true,
  },
  {
    key: "meeting_table",
    name: "Mesa reunion",
    category: "furniture",
    src: `${interiorsPath}/Interiors_free_16x16.png`,
    frame: { x: 16, y: 688, w: 64, h: 32 },
    gridSize: { w: 4, h: 2 },
    collidable: true,
  },
  {
    key: "sofa_lounge",
    name: "Sofa de descanso",
    category: "furniture",
    src: `${interiorsPath}/Interiors_free_16x16.png`,
    frame: { x: 0, y: 1200, w: 96, h: 32 },
    gridSize: { w: 6, h: 2 },
    collidable: true,
  },
  {
    key: "coffee_table",
    name: "Mesa auxiliar",
    category: "furniture",
    src: `${interiorsPath}/Interiors_free_16x16.png`,
    frame: { x: 96, y: 816, w: 48, h: 32 },
    gridSize: { w: 3, h: 2 },
    collidable: true,
  },
  {
    key: "arcade_rug",
    name: "Alfombra arcade",
    category: "floor",
    src: `${interiorsPath}/Interiors_free_16x16.png`,
    frame: { x: 96, y: 384, w: 48, h: 32 },
    gridSize: { w: 3, h: 2 },
  },
  {
    key: "large_rug",
    name: "Alfombra lounge",
    category: "floor",
    src: `${interiorsPath}/Interiors_free_16x16.png`,
    frame: { x: 96, y: 256, w: 64, h: 48 },
    gridSize: { w: 4, h: 3 },
  },
  {
    key: "wall_board",
    name: "Panel de tareas",
    category: "wall",
    src: `${interiorsPath}/Interiors_free_16x16.png`,
    frame: { x: 16, y: 512, w: 32, h: 16 },
    gridSize: { w: 2, h: 1 },
  },
  {
    key: "task_board",
    name: "Panel kanban",
    category: "wall",
    src: `${interiorsPath}/Interiors_free_16x16.png`,
    frame: { x: 16, y: 368, w: 48, h: 32 },
    gridSize: { w: 3, h: 2 },
  },
  {
    key: "wall_map",
    name: "Mapa de procesos",
    category: "wall",
    src: `${interiorsPath}/Interiors_free_16x16.png`,
    frame: { x: 160, y: 1312, w: 48, h: 32 },
    gridSize: { w: 3, h: 2 },
  },
  {
    key: "chair_basic",
    name: "Silla",
    category: "furniture",
    src: `${interiorsPath}/Interiors_free_16x16.png`,
    frame: { x: 64, y: 48, w: 16, h: 16 },
    gridSize: { w: 1, h: 1 },
    collidable: true,
  },
  {
    key: "office_chair_blue",
    name: "Silla azul",
    category: "furniture",
    src: `${interiorsPath}/Interiors_free_16x16.png`,
    frame: { x: 0, y: 736, w: 16, h: 32 },
    gridSize: { w: 1, h: 2 },
    collidable: true,
  },
  {
    key: "stacked_boxes",
    name: "Cajas de archivo",
    category: "furniture",
    src: `${interiorsPath}/Interiors_free_16x16.png`,
    frame: { x: 112, y: 1056, w: 48, h: 32 },
    gridSize: { w: 3, h: 2 },
    collidable: true,
  },
  {
    key: "plant_basic",
    name: "Planta",
    category: "furniture",
    src: `${interiorsPath}/Interiors_free_16x16.png`,
    frame: { x: 112, y: 96, w: 16, h: 32 },
    gridSize: { w: 1, h: 2 },
    collidable: true,
  },
  {
    key: "wardrobe_editor",
    name: "Armario",
    category: "interactive",
    src: `${interiorsPath}/Interiors_free_16x16.png`,
    frame: { x: 160, y: 112, w: 32, h: 32 },
    gridSize: { w: 2, h: 2 },
    collidable: true,
    interactive: true,
  },
];

export function getAvatarDefinition(avatarId: string | null | undefined) {
  return avatarDefinitions.find((avatar) => avatar.id === avatarId) ?? avatarDefinitions[0];
}

export function getAssetDefinition(assetKey: string) {
  return assetDefinitions.find((asset) => asset.key === assetKey);
}
